// NOTE: GLOBAL ACTIONS - START
export const GLOBAL_STATE_START = 'GLOBAL_STATE_START'
export const GLOBAL_STATE_FAIL = 'GLOBAL_STATE_FAIL'

export const GET_USER_THEME = 'GET_USER_THEME'
export const SET_USER_THEME = 'SET_USER_THEME'

export const MOBILE_STATE = 'MOBILE_STATE'

export const SCROLL_STATE = 'SCROLL_STATE'
export const SET_HEIGHT = 'SET_HEIGHT'
export const SET_YOFFSET = 'SET_YOFFSET'
// NOTE: GLOBAL ACTIONS - ENDS

// NOTE: SUBSCRIBE ACTIONS - START
export const ADD_SUBSCRIPTION_START = 'ADD_SUBSCRIPTION_START'
export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS'
export const ADD_SUBSCRIPTION_FAIL = 'ADD_SUBSCRIPTION_FAIL'

export const MODAL_CONTROL = 'MODAL_CONTROL'
// NOTE: SUBSCRIBE ACTIONS - END
