// NOTE: GLOBAL ACTIONS - START
const GLOBAL_STATE_START = 'GLOBAL_STATE_START'
const GLOBAL_STATE_FAIL = 'GLOBAL_STATE_FAIL'

const GET_USER_THEME = 'GET_USER_THEME'
const SET_USER_THEME = 'SET_USER_THEME'

const MOBILE_STATE = 'MOBILE_STATE'

const SCROLL_STATE = 'SCROLL_STATE'
const SET_HEIGHT = 'SET_HEIGHT'
const SET_YOFFSET = 'SET_YOFFSET'
// NOTE: GLOBAL ACTIONS - ENDS

export {
  GLOBAL_STATE_START,
  GLOBAL_STATE_FAIL,
  MOBILE_STATE,
  GET_USER_THEME,
  SET_USER_THEME,
  SCROLL_STATE,
  SET_HEIGHT,
  SET_YOFFSET,
}
