// NOTE: GLOBAL ACTIONS - START
const GLOBAL_STATE_START = 'GLOBAL_STATE_START'
const GLOBAL_STATE_FAIL = 'GLOBAL_STATE_FAIL'

const GET_USER_THEME = 'GET_USER_THEME'
const SET_USER_THEME = 'SET_USER_THEME'

const MOBILE_STATE = 'MOBILE_STATE'
// NOTE: GLOBAL ACTIONS - ENDS

export {
  GLOBAL_STATE_START,
  GLOBAL_STATE_FAIL,
  MOBILE_STATE,
  GET_USER_THEME,
  SET_USER_THEME,
}